/*
 * This source file was generated by the Gradle 'init' task
 */
package de.cm.mandelproto;

import de.cm.mandelproto.gui.MainFrame;

import javax.swing.*;

public class App {

    public static void main(String[] args) {
        SwingUtilities.invokeLater(MainFrame::new);
    }
}
