/*
 * This source file was generated by the Gradle 'init' task
 */
package de.cm.mandelproto;

import de.cm.mandelproto.gui.MainFrame;

public class App {

    public static void main(String[] args) {
        new MainFrame();
    }
}
